project2
MARS-JSU/Internship1400-backEnd-FarhadAlghasi pull request #13
Opened 2021-08-17 17:31 UTC by farhadalghasi

2021-08-17 17:56 UTC, mhmdialireza requested changes

2021-08-17 17:56 UTC, mhmdialireza commented on project phase02/prepare.php
> +    public $expression;
نباید پابلیک باشه ، از بیرون کلاس میشه تغییرش داد

2021-08-17 17:56 UTC, mhmdialireza commented on project phase02/prepare.php
> +        $this->expression = str_replace(array("+x", "-x"), array("+1x", "-1x"), $this->expression);
["+x", "-x"]میتونی از این سینتکس استفاده کنی array("+x", "-x") این قسمت سلیقه ایه ولی بنظر من بجای استفاده از 
یه نکته‌ای هم که وجود داره سینگل کُت چون دنبال متغییر توی رشته نمیگرده یه مقدار سریع تره

2021-08-17 17:56 UTC, mhmdialireza commented on project phase02/prepare.php
> +    private function tvn(array $mono)
نامگذاری اشتباس، کسی که کد رو میخونه متوجه نمیشه

2021-08-17 17:56 UTC, mhmdialireza commented on project phase02/processor.php
> +    protected $obj;
هیچ کلاسی ازین کلاس ارث‌بری نمیکنه ، چرا پرایوت نیستن؟

2021-08-17 17:56 UTC, mhmdialireza commented on project phase02/processor.php
> +    private function makeobj(array $simple)
بزارcamel case اسم متدهارو
ینی بجز کلمه اول بقیه کلمات حرف اولشون بزرگه
makeObj

2021-08-17 17:56 UTC, mhmdialireza commented on project phase02/processor.php
> +    public function strarray()
strArray

2021-08-17 17:56 UTC, mhmdialireza commented on project phase02/page1.php
> +echo "f1($x)= ",$process1->result($x)."<br>";
برای اتصال رشته‌ها باید نقطه بزاری ، اینجا بدون مشکل اجرا میشه؟

2021-08-18 16:42 UTC, farhadalghasi commented on project phase02/page1.php
> +echo "f1($x)= ",$process1->result($x)."<br>";
کانکت ک میکنم بهم میریزه نوشتارش دیگ اینجوری جدا نوشتم تا درست شد

2021-08-20 13:56 UTC, mhmdialireza requested changes

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/page1.php
> +<?php
معمولا اسم صفحه اولو index.php میذارن

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/prepare.php
> +class prepare
نامگذاری تمام کلاس ها باید پاسکال کیس باشه
حروف اول هر کلمه بزرگ و همنام با اسم فایل
LikeThisName

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/prepare.php
> +        if ($this->expression[0] != '+' && $this->expression[0] != '-')
شروط رو باید بشکنی
if (
    $this->expression[0] != '+' && 
    $this->expression[0] != '-'
){
}

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/processor.php
> +            $zp[]=explode('x^',$value);
zp?
نامگذاریت خوانا نیست

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/processor.php
> +    private $obj;
اسم متغیر مشکل داره
مشخص نمیشه چیو نگهداری میکنه
تایپ هم نداره که بفمم ارایس یا نه
obj رو عوض کن

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/pc.php
> +class pc
بنظرم اسم کلاست خوب انتخاب نشده

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/prepare.php
> +        foreach ($mono as $value)
بنظرم ورودی رو بجای $mono
$monos بگیر چون ارایس

بعد توی فوریچ اینو بنویس
$monos as $mono
که دقیق مشخص بشه داری چیکار میکنی

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/prepare.php
> +    public function prepareCoefficient()
حتما واسش تایپ خروجی بزار که مشخص باشه چی ریترن میکنه
الان هربار باید اخر متد رو پیدا کنی که ببینی چیکار میکنه

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/prepare.php
> +                $i++;
این کار خیلی سلقیه ایه و میتونی انجام ندی
ولی بنظرم میشه کوتاه تر نوشت
$temp[$i++] = $value;

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/processor.php
> +    private function makeObj(array $zp)
zp
حتما اسمشو درست کن

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/processor.php
> +    private function toString(array $str)
وقتی متغیرت آرایس باید حتما به اسمش توجه کنی 
$strings
اس جمع رو بزار که وقتی یکم رفتی پایین تر بدونی با آرایه طرفی

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/processor.php
> +        foreach ($str as $value)
foreach ($strings as $string)

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/processor.php
> +        echo $string;
با این کار هیچوقت نمیتونی مقدار خروجی رو تو یه متغییر دریافت کنی
فقط خروجی میده
اینجا ریترن کن
خروجی متد رو  هم اون بالا مشخص کن

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/processor.php
> +        echo $res;
ریترن کن

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/processor.php
> +            if($value->getpower()!=0 && $value->getcoefficient()!=0 && $value->getpower()!=1)
if(
$value->getpower()!=0 && 
$value->getcoefficient()!=0 && 
$value->getpower()!=1
)
اینجوری خوانایی بالاتر میره

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/processor.php
> +                $dev[]=($value->getcoefficient()*$value->getpower()).'x^'.($value->getpower()-1);
اسم کامل بزار
dev مشخص نمیکنه چی رو نگهداری میکنه

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/processor.php
> +        $this->toString($dev);
متد toString باعث شده کل کدت خراب شه
حتی اینجا هم نمیتونی چند جمله‌ای مشتق رو بگیری

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/pc.php
> +    private $power;
تایپ مشخص کن حتما

2021-08-20 13:56 UTC, mhmdialireza commented on project phase02/pc.php
> +    }
یه کاری که میتونی انجام بدی و توی php 8 اضافه شده
و البته هیچ الزامی براش وجود نداره 
اینکه که 
private $coefficient;
private $power;

public function __construct($coefficient,$power)
    {
        $this->coefficient=$coefficient;
        $this->power=$power;
    }

خطوط بالارو میشه تو 
public function __construct(
private $coefficient
private $power
){}
خلاصه کرد

2021-08-20 22:06 UTC, mhmdialireza approved these changes

2021-08-21 10:55 UTC, RAAvenger requested changes
<div dir="rtl">
سلام خسته نباشی

کد خوبی نوشتی ولی ساختارت غلطه، توی ساختار کدت باید یک تحلیلگر داشته باشی که اینجا وظیفه تحلیلگر یه جورایی بین Prepare و Processor تقسیم شده و باید توی یک کلاس جمع بشه

2021-08-21 10:55 UTC, RAAvenger commented on project phase02/prepare.php
> +    private function preparePower(array $monos)
<div dir="rtl">
بین متدها اینتر بزن.

2021-08-21 10:55 UTC, RAAvenger commented on project phase02/processor.php
> +    }
<div dir="rtl">
کار این چیه؟

2021-08-21 10:55 UTC, RAAvenger commented on project phase02/processor.php
> +                $string=str_replace('x^1','x',$string);
<div dir="rtl">
این قسمت برای x^12 به مشکل نمیخوره؟

2021-08-21 10:55 UTC, RAAvenger commented on project phase02/processor.php
> +    }
<div dir="rtl">
به جای اینکار بیا  و برای هر PowerCofficient متد __toString() رو رونویسی کن که بتونی اینجا ازش برای تبدیل کل چند جمله‌ای به رشته استفاده کنی.

2021-08-23 14:04 UTC, farhadalghasi commented on project phase02/processor.php
> +    }
ضریب و توانی که داریم و میاد دوبارع بصورت تک جمله ای تو آرایه میذاره بعد تابع استرینگ رو صدا میزنه در نهایت همون استرینگ رو بر میگردونه

2021-08-23 14:04 UTC, farhadalghasi commented on project phase02/processor.php
> +                $string=str_replace('x^1','x',$string);
درست شد

2021-08-23 14:10 UTC, RAAvenger commented on project phase02/processor.php
> +    }
چرا مونو برنمیگردونه؟

2021-08-23 14:27 UTC, farhadalghasi commented
خب مونوش به کارم نمیاد ما برای خروجی یه چند جمله ای میخوایم دیگ

‫‪Reza Adibi‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۲۳ اوت ۲۰۲۱
ساعت ۱۸:۴۰ نوشت:‬

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In project phase02/processor.php
> <https://github.com/MARS-JSU/Internship1400-backEnd-FarhadAlghasi/pull/13#discussion_r694007707>
> :
>
> > +    public function makeMono():string
>
> +    {
>
> +        foreach ($this->powerCofficientArray as $value)
>
> +        {
>
> +            if($value->getcoefficient()!=0)
>
> +            {
>
> +                $array[]=$value->getcoefficient().'x^'.$value->getpower();
>
> +            }
>
> +        }
>
> +        $string=$this->toString($array);
>
> +        return $string;
>
> +    }
>
>
> چرا مونو برنمیگردونه؟
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MARS-JSU/Internship1400-backEnd-FarhadAlghasi/pull/13#discussion_r694007707>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU66VPHVR76WER6AEYGIZPTT6JJELANCNFSM5CKKU5UQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-25 14:46 UTC, mhmdialireza requested changes

2021-08-25 14:46 UTC, mhmdialireza commented on project phase02/PowerCofficient.php
> +    public function __tostring() : string
__toString
این مجیک متد با S توی هسته php تعریف شده

2021-08-25 14:46 UTC, mhmdialireza commented on project phase02/processor.php
> +    private function powerCofficientArraySort()
این متد یه مدت دیگه رو صدا میکنه
چرا از اول همون متدوصدا نمیزنی؟

2021-08-25 14:46 UTC, mhmdialireza commented on project phase02/processor.php
>          $this->sortig($this->powerCofficientArray);
powerCofficientArray یکی از اعضای کلاسه
چرا پاسش میدی بین متدا وقتی که خودشون دسترسی دارن؟

2021-08-25 14:46 UTC, mhmdialireza commented on project phase02/processor.php
>      private function simplify($obj)
باید پابلیک باشه
شاید کاربر خودش بخواد ساده کنه

2021-08-25 14:46 UTC, mhmdialireza commented on project phase02/processor.php
> +                        settype($newcoef,'float');
خیلی ازین تابع استفاده کردی
چرا از همونجایی که داری یک جمله ای هاتو میسازی یبار به عدد اعشاری تبدیلشون نمیکنی که هربار نخوای دوباره تبدیل کنی

2021-08-25 14:46 UTC, mhmdialireza commented on project phase02/processor.php
> +    public function toString() : string
__toString

2021-08-25 14:46 UTC, mhmdialireza commented on project phase02/index.php.php
> +echo "derivative exp1= ",$process1->derivative()->toString()."<br>";
اونجا از مجیک متد پی اچ پی استفاده کردی که نخوای متد
toString رو صدا کنی
echo "derivative exp1= ",$process1->derivative()."<br>";

2021-08-25 14:46 UTC, mhmdialireza commented on project phase02/prepare.php
> +            $cofficientpowers[]=explode('x^',$mono);
اینجا به فلوت تبدیل کن

2021-08-25 17:47 UTC, RAAvenger approved these changes

2021-08-25 17:47 UTC, RAAvenger commented on project phase02/processor.php
> +    }
<div dir=rtl>
در چه موقعیت‌هایی ازش استفاده می‌کنی؟

2021-08-25 17:47 UTC, RAAvenger commented on project phase02/processor.php
> +                $string=str_replace('x^1','x',$string);
<div dir=rtl>
هروقت تغییراتت رو کامیت کردی بگو.

2021-08-29 14:35 UTC, hamedgk requested changes

2021-08-29 14:35 UTC, hamedgk commented on project phase02/interfaces/powerCofficientInterface.php
> +{
اینترفیس ها باید پاسکال کیس باشن برای مثال SimplifyInterface
این قضیه برای نام پوشه شامل اینترفیس و نام فایل هم صادقه

2021-08-29 14:35 UTC, hamedgk commented on project phase02/prepare.php
> +    public function __construct($expression)
نوعشون رو مشخص کن

2021-08-29 14:35 UTC, hamedgk commented on project phase02/simplify.php
> +class simplify implements simplifyInterface
اسم کلاس هم باید پاسکال کیس باشه برای مثال Simplify

2021-08-29 14:35 UTC, hamedgk commented on project phase02/PowerCofficient.php
> +}
برای اینکه از اصل اول سالید پیروی کنی. یه کلاس جداگانه برای این محاسبات در نظر بگیر

2021-08-31 06:14 UTC, merged